<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            array('parent_id' => NULL,'name_id' => 'Ganti Filter Udara','price' => '8400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Busi','price' => '12000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '75','name_id' => 'Ganti lampu depan','price' => '12000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '75','name_id' => 'Ganti Lampu Belakang','price' => '8400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '75','name_id' => 'Ganti Lampu Sen','price' => '8400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '75','name_id' => 'Ganti Klakson','price' => '8400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '20','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '75','name_id' => 'Ganti Lampu Speedometer','price' => '14400','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '20','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '75','name_id' => 'Ganti Lampu Senja','price' => '8400','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '15','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '77','name_id' => 'Tambah Angin','price' => '2400','icon_id' => NULL,'duration_easy' => '5','duration_hard' => '5','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '76','name_id' => 'Ganti Kampas Rem Depan','price' => '14400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '76','name_id' => 'Ganti Kampas Rem Belakang','price' => '18000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '77','name_id' => 'Ganti Rantai','price' => '12000','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '20','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '77','name_id' => 'Setel Rantai','price' => '8400','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '15','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '77','name_id' => 'Potong Rantai','price' => '14400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '78','name_id' => 'Ganti + Pemeriksaan Selang Bensin','price' => '18000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '40','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '82','name_id' => 'Pengisian Air ACCU','price' => '6000','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '25','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '82','name_id' => 'Kuras + Ganti Air ACCU','price' => '18000','icon_id' => NULL,'duration_easy' => '25','duration_hard' => '25','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '79','name_id' => 'Ganti Oli Mesin','price' => '8400','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '15','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '79','name_id' => 'Ganti Oli Samping','price' => '8400','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '15','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Ganti Shockbreaker Depan','price' => '42000','icon_id' => NULL,'duration_easy' => '120','duration_hard' => '150','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Ganti Shockbreaker Belakang','price' => '24000','icon_id' => NULL,'duration_easy' => '45','duration_hard' => '90','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '80','name_id' => 'Setel Klep','price' => '18000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '45','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '80','name_id' => 'Setel Kopling','price' => '12000','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '20','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '76','name_id' => 'Tambah Minyak Rem','price' => '8400','icon_id' => NULL,'duration_easy' => '10','duration_hard' => '25','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '76','name_id' => 'Kuras Minyak Rem','price' => '18000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '25','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Tambah Cairan Radiator','price' => '14400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '81','name_id' => 'Setel Stang kemudi','price' => '18000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Setel Karburator','price' => '12000','icon_id' => NULL,'duration_easy' => '10','duration_hard' => '15','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Setel Grip Gas','price' => '6000','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '15','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Pasang Spion','price' => '6000','icon_id' => NULL,'duration_easy' => '5','duration_hard' => '5','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Kunci Kontak','price' => '24000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '60','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Grip Gas','price' => '12000','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '15','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Rumah Grip Gas','price' => '24000','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '30','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Rumah Saklar Kanan','price' => '30000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti kabel Gas Dalam','price' => '30000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Kabel Gas 1 Set','price' => '30000','icon_id' => NULL,'duration_easy' => '45','duration_hard' => '60','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Tombol Stater','price' => '18000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '35','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Handle Rem','price' => '12000','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '25','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Master Rem','price' => '42000','icon_id' => NULL,'duration_easy' => '60','duration_hard' => '90','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Selang Minyak Rem','price' => '42000','icon_id' => NULL,'duration_easy' => '60','duration_hard' => '90','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Seal Master Rem','price' => '42000','icon_id' => NULL,'duration_easy' => '60','duration_hard' => '90','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Servis Kampas Rem Depan','price' => '42000','icon_id' => NULL,'duration_easy' => '60','duration_hard' => '90','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Disc Brake','price' => '24000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Bearing Depan','price' => '18000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '40','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Ban Luar','price' => '18000','icon_id' => NULL,'duration_easy' => '35','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Ban Dalam','price' => '12000','icon_id' => NULL,'duration_easy' => '35','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Pentil Tubles','price' => '24000','icon_id' => NULL,'duration_easy' => '35','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti kabel Speedometer','price' => '18000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Swich Rem','price' => '8400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Flasher Sen','price' => '18000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti kepala Body Depan','price' => '24000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti kepala Body Belakang','price' => '24000','icon_id' => NULL,'duration_easy' => '40','duration_hard' => '50','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Speedometer','price' => '30000','icon_id' => NULL,'duration_easy' => '40','duration_hard' => '50','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Reflector Sen + Lampu Depan','price' => '30000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Rumah Saklar','price' => '30000','icon_id' => NULL,'duration_easy' => '45','duration_hard' => '55','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Tombol Sen','price' => '14400','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '40','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Tombol Klakson','price' => '14400','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '40','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Tombol Lampu Jauh Dekat','price' => '14400','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '40','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Piting Lampu Depan','price' => '18000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Piting Lampu Sen','price' => '18000','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Handle Kopling','price' => '8400','icon_id' => NULL,'duration_easy' => '15','duration_hard' => '25','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Coil','price' => '24000','icon_id' => NULL,'duration_easy' => '45','duration_hard' => '60','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Spakbor Belakang','price' => '36000','icon_id' => NULL,'duration_easy' => '60','duration_hard' => '90','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Tangki/Keran Bensin/Vacum','price' => '30000','icon_id' => NULL,'duration_easy' => '35','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Bearing Belakang','price' => '24000','icon_id' => NULL,'duration_easy' => '45','duration_hard' => '60','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Gear Set','price' => '30000','icon_id' => NULL,'duration_easy' => '45','duration_hard' => '60','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Paking Knalpot','price' => '8400','icon_id' => NULL,'duration_easy' => '20','duration_hard' => '30','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Bos Arm','price' => '36000','icon_id' => NULL,'duration_easy' => '60','duration_hard' => '90','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Ban Belakang','price' => '24000','icon_id' => NULL,'duration_easy' => '45','duration_hard' => '60','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Ganti Mika Reflektor Lampu Belakang','price' => '24000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '45','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Pasang Plat Nomer','price' => '8400','icon_id' => NULL,'duration_easy' => '10','duration_hard' => '15','is_easy' => '0','is_medium' => '1','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Tuneup Bronze','price' => '52500','icon_id' => NULL,'duration_easy' => '60','duration_hard' => '60','is_easy' => '0','is_medium' => '0','is_tuneup' => '1','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Tuneup Silver','price' => '147500','icon_id' => NULL,'duration_easy' => '150','duration_hard' => '150','is_easy' => '0','is_medium' => '0','is_tuneup' => '1','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Tuneup Gold','price' => '187500','icon_id' => NULL,'duration_easy' => '210','duration_hard' => '210','is_easy' => '0','is_medium' => '0','is_tuneup' => '1','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '73','name_id' => 'Pemeriksaan Fungsi Kelistrikan','price' => '60000','icon_id' => NULL,'duration_easy' => '110','duration_hard' => '145','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '72','name_id' => 'Pemeriksaan Fungsi Pengereman','price' => '25000','icon_id' => NULL,'duration_easy' => '70','duration_hard' => '110','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '72','name_id' => 'Pemeriksaan Fungsi Roda','price' => '15000','icon_id' => NULL,'duration_easy' => '50','duration_hard' => '55','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '73','name_id' => 'Pemeriksaan Jalur Bahan Bakar','price' => '18000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '40','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '72','name_id' => 'Pemeriksaan Oli','price' => '15000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '30','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '74','name_id' => 'Pemeriksaan Putaran Stationer Mesin','price' => '25000','icon_id' => NULL,'duration_easy' => '35','duration_hard' => '65','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '74','name_id' => 'Pemeriksaan Pergerakan Stang Kemudi','price' => '20000','icon_id' => NULL,'duration_easy' => '10','duration_hard' => '20','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '82','name_id' => 'Pemeriksaan ACCU','price' => '20000','icon_id' => NULL,'duration_easy' => '40','duration_hard' => '40','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '73','name_id' => 'Pemeriksaan Fungsi Suspensi','price' => '60000','icon_id' => NULL,'duration_easy' => '180','duration_hard' => '255','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Pemeriksaan Block CVT','price' => '50000','icon_id' => NULL,'duration_easy' => '230','duration_hard' => '425','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '1','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Isi Oli Shock','price' => '6000','icon_id' => NULL,'duration_easy' => '10','duration_hard' => '10','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '84','name_id' => 'Ganti per slah','price' => '25000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '60','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '84','name_id' => 'Ganti as slah','price' => '25000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '60','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Ganti V-Belt','price' => '25000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '60','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '84','name_id' => 'Ganti Roller','price' => '25000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '60','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Pembersihan Rumah Roller','price' => '25000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '60','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Ganti Stempelt CVT','price' => '6000','icon_id' => NULL,'duration_easy' => '10','duration_hard' => '10','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Pembersihan busa saringan CVT','price' => '6000','icon_id' => NULL,'duration_easy' => '10','duration_hard' => '10','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Pembersihan Pully Roller','price' => '18000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '45','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '83','name_id' => 'Pembersihan rumah kampas dan centripugal ','price' => '25000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '60','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '72','name_id' => 'Pemeriksaan baud dan mur','price' => '0','icon_id' => NULL,'duration_easy' => '5','duration_hard' => '5','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '72','name_id' => 'Pembersihan Karburator','price' => '0','icon_id' => NULL,'duration_easy' => '25','duration_hard' => '25','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '72','name_id' => 'Pemeriksaan dan Pengisian Air Radiator','price' => '0','icon_id' => NULL,'duration_easy' => '5','duration_hard' => '5','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => '72','name_id' => 'Pembersihan Busi','price' => '0','icon_id' => NULL,'duration_easy' => '5','duration_hard' => '15','is_easy' => '0','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0),
            array('parent_id' => NULL,'name_id' => 'Testing','price' => '150000','icon_id' => NULL,'duration_easy' => '30','duration_hard' => '60','is_easy' => '1','is_medium' => '0','is_tuneup' => '0','is_package' => '0','created_at' => new Carbon(),'updated_at' => new Carbon(), 'recommendation_up' => 0, 'duration_medium' => 0, 'is_medium' => 0)
        );

        DB::table('services')->insert( $data );
    }
}
